# Generated by Django 4.2.3 on 2023-07-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('features', models.TextField(verbose_name='Özellikler')),
                ('picture', models.ImageField(upload_to='product_images', verbose_name='Resim')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fiyat')),
            ],
        ),
    ]
